#!/bin/bash
xl destroy hyperbench
losetup /dev/loop0 /opt/os.img
kpartx -av /dev/loop0
mount /dev/mapper/loop0p1 /opt/os
cp ./out/hyperbench* /opt/os/boot
umount /opt/os
losetup -d /dev/mapper/loop0p1
xl create -c ./script/hyperbench.hvm


